_extends: .github

repository:
  name: app
  description: Colophon Dashboard
  topics: colophon, dashboard
  homepage: https://colophon.id
  private: false
  has_issues: true
  has_wiki: false
  has_downloads: false
  has_projects: false
  default_branch: master
  allow_squash_merge: true
  allow_merge_commit: false
  allow_rebase_merge: true
