version: '3.2'

services:
  db:
    build: db

  server:
    build: app
    depends_on:
      - db

    ports:
      - '3000:3000'
      - '9229:9229'

    volumes:
      - ${PRIVATE_KEY_PATH}:/src/key.pem
