version: '3.2'

services:
  db:
    build: db
    environment:
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD

  app:
    build: .

    links:
      - db

    depends_on:
      - db

    ports:
      - 3000:${COLOPHON_PORT}
      - '9229:9229'

    environment:
      - GITHUB_APP_ID
      - GITHUB_APP_LINK
      - GITHUB_CLIENT_ID
      - GITHUB_CLIENT_SECRET
      - GITHUB_PRIVATE_KEY
      - GITHUB_WEBHOOK_SECRET
      - COLOPHON_LINK
      - COLOPHON_PORT
      - COLOPHON_SESSION_SECRET
      - POSTGRES_HOST
      - POSTGRES_PORT
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD

