version: '3.2'

services:
  db:
    build: db
    environment:
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD

  server:
    build: app

    links:
      - db

    depends_on:
      - db

    ports:
      - '3000:3000'
      - '9229:9229'

    volumes:
      - ${PRIVATE_KEY_PATH}:/src/key.pem

    environment:
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - WEBHOOK_PROXY_URL
      - APP_ID
      - PRIVATE_KEY_PATH
      - WEBHOOK_SECRET
      - CLIENT_ID
      - CLIENT_SECRET
      - SESSION_SECRET
